openapi: 3.0.3
info:
  title: FOFA Search API
  description: FOFA Search Engine API ile arama sorguları yapmayı sağlar.
  version: 1.0.0

servers:
  - url: https://fofa.info
    description: FOFA API Ana URL

components:
  securitySchemes:
    ApiKeyQuery:
      type: apiKey
      in: query
      name: key 

paths:
  /api/v1/search/all:
    get:
      summary: FOFA üzerinde arama yap
      description: FOFA'nın tüm kaynaklarında dork sorgusu yapar
      parameters:
        - name: key
          in: query
          required: true
          description: FOFA API key
          schema:
            type: string
        - name: q
          in: query
          required: true
          description: FOFA dork sorgusu (örnek: `app="nginx"`)
          schema:
            type: string
        - name: size
          in: query
          required: false
          description: Döndürülecek sonuç sayısı (varsayılan: 10)
          schema:
            type: integer
        - name: fields
          in: query
          required: false
          description: Hangi alanların döneceği, virgülle ayrılmış (örnek: ip,host,port)
          schema:
            type: string
      responses:
        '200':
          description: Başarılı istek
          content:
            application/json:
              schema:
                type: object
                properties:
                  mode:
                    type: string
                  page:
                    type: integer
                  size:
                    type: integer
                  results:
                    type: array
                    items:
                      type: array
                      items:
                        type: string
        '401':
          description: Yetkisiz - API key geçersiz
        '400':
          description: Geçersiz istek
security:
  - ApiKeyQuery: []
